// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAszOJcK5LD5yE-H4PQHDnBG1fpsweq22U',
    appId: '1:606865152248:web:4f079e8775629ef3cf830d',
    messagingSenderId: '606865152248',
    projectId: 'my-closet-d4fbd',
    authDomain: 'my-closet-d4fbd.firebaseapp.com',
    storageBucket: 'my-closet-d4fbd.appspot.com',
    measurementId: 'G-5J31W1BBPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsrdx-D_IdVsPOQQ7lOC8Ud596pTsABAE',
    appId: '1:606865152248:android:0fde8bfca3a5f45dcf830d',
    messagingSenderId: '606865152248',
    projectId: 'my-closet-d4fbd',
    storageBucket: 'my-closet-d4fbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcdf7NSz6Okic5c9UxWqRGr4O3TCVYLSE',
    appId: '1:606865152248:ios:119ded5c051625dbcf830d',
    messagingSenderId: '606865152248',
    projectId: 'my-closet-d4fbd',
    storageBucket: 'my-closet-d4fbd.appspot.com',
    iosBundleId: 'com.example.myCloset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcdf7NSz6Okic5c9UxWqRGr4O3TCVYLSE',
    appId: '1:606865152248:ios:76a9db36fb8acf68cf830d',
    messagingSenderId: '606865152248',
    projectId: 'my-closet-d4fbd',
    storageBucket: 'my-closet-d4fbd.appspot.com',
    iosBundleId: 'com.example.myCloset.RunnerTests',
  );
}
